R Tidyverse Applications
Manipulate Data

```{r}
#RUN FIRST
library(readxl)
library(tidyr)
#load in sales data from Excel file by sheet number
sales <- read_excel("KinetEco Sales.xlsx", sheet= 1)
sales
```

```{r}
#Split EmpName column into first and last name
sales %>% separate_wider_delim(EmpName, delim = " ", names = c("EmpFirstName", "EmpLastName"))
```

```{r}
#Unite ProdNumber and ProdName columns
sales %>% unite("Product", ProdNumber:ProdName, sep = "- ", remove = FALSE)
```

```{r}
#Split Product column by expanding data
sales_product <- sales %>% unite("Product", ProdNumber:ProdName, sep = "/", remove = FALSE)
sales_product %>% separate_longer_delim(Product, delim = "/")
```

```{r}
#Expand ProdCategory column to view all values
sales %>% expand(ProdCategory)
```

```{r}
#View all possible OrderType and CustType combinations
sales %>% expand(OrderType, CustType)
```

```{r}
#Pivot data wider by OrderType and Order Total
sales %>% pivot_wider(names_from= OrderType, values_from= "Order Total")
```

```{r}
#Create order_type_quantity tibble
order_type_quantity <- tibble(ProdCategory = c("Batteries", "EV charger", "Grid Tie Inverters", "Landscape lighting", "Lightbulbs", "Solar panels", "Wind harvester"),
                              Retail = c(1332, 32, 112,3971, 3626, 2104,202),
                              Wholesale = c(542, 13, 246, 167, 629, 998, 177))
order_type_quantity
```

```{r}
#Pivot data longer by ProdCategory
order_type_quantity %>% pivot_longer(cols=2:3, names_to = "OrderType", values_to= "TotalQuantity")
```

```{r}
#Pivot data longer by ProdCategory version 2
order_type_quantity %>% pivot_longer(!ProdCategory, names_to = "OrderType", values_to= "TotalQuantity")
```
