R Tidyverse Applications
Manipulate Data

```{r}
#RUN FIRST
library(readxl)
library(forcats)
#load in sales data from Excel file by sheet number
sales <- read_excel("KinetEco Sales.xlsx", sheet= 1)
sales$CustType <- factor(sales$CustType)
sales$OrderType <- factor(sales$OrderType)
sales$EmpTitle <- factor(sales$EmpTitle)
sales$SalesReg <- factor(sales$SalesReg)
sales
```

```{r}
#Get levels of OrderType factor column
levels(sales$OrderType)
```

```{r}
#Manually change order of levels of OrderType factor column
sales$OrderType <- fct_relevel(sales$OrderType, c("Wholesale", "Retail"))
levels(sales$OrderType)
```

```{r}
#Get levels of SalesReg factor column
levels(sales$SalesReg)
```

```{r}
#Change order of levels by frequency of SalesReg factor column
sales$SalesReg <- fct_infreq(sales$SalesReg)
levels(sales$SalesReg)
```

```{r}
#Change order of levels by order of appearance of SalesReg factor column
sales$SalesReg <- fct_inorder(sales$SalesReg)
levels(sales$SalesReg)
```

```{r}
#Reverse order of levels of SalesReg factor column
sales$SalesReg <- fct_rev(sales$SalesReg)
levels(sales$SalesReg)
```

```{r}
#Shift order of levels of SalesReg factor column
sales$SalesReg <- fct_shift(sales$SalesReg)
levels(sales$SalesReg)
```

```{r}
#Shuffle order of levels of SalesReg factor column
sales$SalesReg <- fct_shuffle(sales$SalesReg)
levels(sales$SalesReg)
```

```{r}
#Change order of levels of SalesReg factor column by another column
sales$SalesReg <- fct_reorder(sales$SalesReg, sales$"Order Total")
levels(sales$SalesReg)
```

```{r}
#Get levels of CustType factor column
levels(sales$CustType)
```

```{r}
#Manually change level values of CustType factor column
sales$CustType <- fct_recode(sales$CustType, B2B = "Business", B2C = "Individual")
levels(sales$CustType) 
```

```{r}
#Get levels of EmpTitle factor column
levels(sales$EmpTitle)
```

```{r}
#Collapse level values of EmpTitle factor column
sales$EmpTitle <- fct_collapse(sales$EmpTitle, "Senior Associate"= c("Senior Sales Associate", "Senior Sales Representative"))
levels(sales$EmpTitle)
```

```{r}
#Collapse level values of EmpTitle factor column into "Other"
sales$EmpTitle <- fct_other(sales$EmpTitle, keep= c("Senior Associate","Sales Associate","Sales Associate I", "Sales Associate II", "Sales Associate III"))
levels(sales$EmpTitle)
```

```{r}
#Create numeric level values of EmpTitle factor column
sales$EmpTitle <- fct_anon(sales$EmpTitle)
levels(sales$EmpTitle)
```

